server:
  port: 8500

logging:
  level:
    org.springframework: DEBUG

spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: admin
    password: password
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379

