server:
  port: 8500

logging:
  level:
    org.springframework: DEBUG

spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: admin
    password: password
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379


rest-client:
  accounts-loan-url: http://localhost:8400/accounts-loan
  accounts-current-url: http://localhost:8200/accounts-current/
  accounts-deposit-url: http://localhost:8300/accounts-deposit/
  individual-url: http://localhost:8100/individuals/








